title: "Ranmocy's Fragments"
description: "My Brain, My Treasure."
author: Ranmocy
email: Ranmocy@gmail.com

# paginate: 8
categories_group:
  life:
    - blog
    - diary
    - dream
    - poem
  idea:
    - motto
    - idea
    - remark
    - philosophy
  work:
    - tech
    - piece
motto:
  blog: 旅行日志
  diary: 一个欲望灼烧者艰难写下的自白。
  dream: 最真实总是梦境
  poem: 用诗歌来拯救自我
  motto: 一句话评点世界
  idea: 思维碎片，漂浮在名叫头脑的海洋。
  remark: 从这个世界剥离出的抽象
  philosophy: 我在教导你们世界运行的原动力。你们听之，想之，就忘之吧。
  tech: 技术宅拯救世界。
  piece: What I did define what I am.


permalink:     /:categories/:title/
url:         http://ranmocy.info
