* 宣言
  我在德国曾经交流学习过一个月，这段时间里面给我的最大的感受来源于一个困惑。我不明白为什么德国人看起来一个个闲的要死但是整个国家却能保持极高的生产总值和高福利待遇。
  相反，中国人成天拼死拼活的，人均生产总值却远低于欧洲各国。为什么？

  集光社并不是一个商业性质的组织，它不以盈利为目的。但是事实上它可以包含商业行为在其中。
  我成立这个组织的目的在于为不同学科之间的有想法的一类人提供交流的平台。
  事实上我们想到达芬奇一类的大师的时候，都会为他们在数个领域中同时做出了巨大的贡献而赞叹不已。
  而我认为，现代科学全部发源于古希腊的自然哲学这一分支而演化而来。其在根源上是十分相像的存在，那么，我们可不可以就认为掌握了其中一个学科，可以对另外一个学科的理解有着巨大的帮助呢？
  我认为这是显而易见的。

* 目标群体
  现在，这个组织的目标群体的主体是大学生。原因是，你们已经开始接触社会，脱离了压抑的体制教育，虽然我对中国大学的教育抹杀学生学科兴趣这一点十分的厌恶，但是优秀的学生已经开始拥有自己的想法，和渴望表达的欲望。
  你们是我所认识的人当中，我十分欣赏的一类人。你们有一个特点是集光社所关注的，就是在自己的领域中有着高于一般人的理解，有想法有热情的一类人。
  最重要的是第一个特点，就是对自己所在的领域有高于一般人的理解。
  集光社的存在目的之一就是在于跨学科的交流，我要你将你们对

* 原则
** 精英原则
   这个不是用来建立优越感而存在的原则。这个原则是集光社能存在下去的一个保障条件。
   现在社会中的信息爆炸给我们已经带来了很大的负担。我一直不能忍受刷类似人人的timeline这种低效率的信息接受行为，我认为这是在浪费时间，是在扼杀自己的青春。
   我想要提供最优秀的讲座，这些讲座是值得你去回味的讲座，而不是像RSS一样只是告诉你发生了什么事情。不，我们要告诉你的是我们对这个世界的思考。
   我们从信息过少的极端跳到了信息过多的另一个极端，我要将思考重新引会我们的生活之中，对每个细小的事物的思考都会给我们带来丰富的收益。来重新产生信息与思考的平衡。我也认为这是在座的各位的一个渴望。
   这个讲座是在开放的场地进行的，你们随时可以带朋友过来，但是集光社的成员加入是需要邀请和审核的。讲座的时间信息也只会在内部广播。
** 效率
   你也许会说这是为了调节自己的压力，做些这样完全不需要动脑袋的事情可以放松自己的压力。
   但我可以十分负责任的告诉你，调节压力的方法成千上万，而远比刷人人有意义的方式亦成百上千。调节压力不是这种行为的理由。
   而我更想说的是，当你觉得自己压力很大的时候，往往就是你自己没有安排好自己的时间所导致的。人的潜力大的出乎你的想象。想想我们考试周的时候，一天学习完一科的时候。那时候你的信息接受密度亦不是你真正的极限。
   我十分强烈的推荐大家了解一下GTD时间管理，在你处理数量繁多而琐碎的事情的时候有着强大的威力。以后我会单独做一个讲座。
** 这不只是个讲坛，这是一个组织
   这是另外一个目的。每个人在日后都会在自己的领域中有着优秀的建树，这是我所看重的一点。
** 新鲜血液
   我不想改造任何人，使他适应我们，我只想吸收跟我相似的人，让他认可我们。
** 只要有一个人来听，这个讲座就有意义
   思想的传播是十分困难的一件事情，是因为其实语言远远不够复杂到可以比较精确的描述我们自身的想法。我们唯一能做的就是用大量的语言不断的修正，以期望能无限逼近我们真实的想法。

* 光线
  我很喜欢光线这个词，首先它是世界上跑的最快的东西，是最难以超越其速度的存在。
  其次，我们说太阳光是由七色组成，但是事实上是它是一个完整的光谱所组成的。它是由丰富的细节所组成的，正像是我们在做一个设计的时候所要关注的每一个细节一样。

* 理想主义




* TODO Affairs
** Speech Pre
** Logo Design
** Record
** Website
*** Live
