name: Publish pages

on:
  push:
    branches: [ master ]

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1.84.0
    - run: bundle install
    - run: bundle exec rake generate
    - run: cd /tmp/brain
    - uses: lowply/deploy-firebase@v0.0.5
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        FIREBASE_PROJECT: ranmocy-me
    - name: Push to gh-pages
      run: |
        git checkout gh-pages
        rm -r ./* || true
        cp -r /tmp/brain/* .
        mv cname c && mv c CNAME || true
        git add .
        git commit -m 'Updated at `date`.'
        git push origin gh-pages:gh-pages
