name: Publish pages

on:
  push:
    branches: [ master ]

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1.84.0
    - run: bundle exec rake publish
